### PR TITLE
Update certbot readme's with entrust end of support

### PR DESCRIPTION
**Pull request by TimCsaky**
# Description
with Entrust dropping support for certbot (using the V1 entrust endpoint) we need to let BC users know Entrust is no longer an option for certs in a production environment.

## Types of changes

 Documentation (non-breaking change with enhancements to documentation) 

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by WadeBarnes — CHANGES_REQUESTED** [review]
@TimCsaky, Are you able to provide links to the Entrust wording on this subject?  Are they planning support for the `ACME v2` endpoints?  For example, Let Encrypt stopped using `ACME v1` back in June of 2020.

There is a hint that Entrust does/may/will support `ACME v2` here, https://www.entrust.com/blog/2023/04/googles-90-day-proposal-for-tls-certificates/, and here, https://www.entrust.com/-/media/documentation/datasheets/certificate-enrollment-gateway-ss.pdf?la=en&hash=06208F40D2C9A6E0B9E98CDE8B12C759.

**Comment by TimCsaky** [comment]
> 
The only Entrust docs i see are here: https://www.entrust.com/knowledgebase/ssl/how-to-use-acme-to-install-ssl-tls-certificates-in-entrust-certificate-services-apache
The BC gov Entrust server does not currently support V2. Certbot will also require some modification if V2 becomes an option: https://en.wikipedia.org/wiki/Automatic_Certificate_Management_Environment#API_versions

**Comment by WadeBarnes** [comment]
Certbot does work with the ACME v2 endpoints, I'm using Certbot with the Let's Encrypt ACME v2 endpoints on a few of our demo services for the DITP team.

**Comment by WadeBarnes** [comment]
Based on the documentation I found I don't think we can confidently make the statement that Entrust has discontinued support for Certbot.  I do recall somewhere some working around them discontinuing support for ACME v1, but Cerbot supports ACME v2, and the documents seem to indicate Entrust is or will be supporting ACME v2.

**Comment by WadeBarnes** [comment]
Do we know if someone on the BC Gov side is looking into Entrusts support for ACME v2?

**Comment by TimCsaky** [comment]
Thanks @WadeBarnes . Yes important to get these details clear.
i've been advised by middle-tier/infrastructure that the entrust service they use does not support acme v2 api.
They've asked that for entrust certs the requests are handled manually. (https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/Generating+a+CSR)

**Review by jujaga — APPROVED** [review]

**Comment by bcgov-nr-csst** [comment]
Merge overriding as this PR only contains readme documentation changes.

**Pull request merged**
